"""add refresh_token table for auth

Revision ID: 78017cfa55be
Revises: 8516f1dd9d51
Create Date: 2026-05-28 23:00:55.799854

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78017cfa55be'
down_revision: str | None = '8516f1dd9d51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index('ix_refresh_token_expires_at', 'refresh_token', ['expires_at'], unique=False)
    op.create_index('ix_refresh_token_user_id', 'refresh_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_token_user_id', table_name='refresh_token')
    op.drop_index('ix_refresh_token_expires_at', table_name='refresh_token')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
