"""add superseded_at and superseded_by_id to messages

Revision ID: 7c9c487e85ba
Revises: ee85fab69b46
Create Date: 2026-05-26 20:56:16.737409

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9c487e85ba'
down_revision: str | None = 'ee85fab69b46'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('superseded_by_id', sa.UUID(), nullable=True))
    op.create_index('ix_messages_superseded_by', 'messages', ['superseded_by_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['superseded_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index('ix_messages_superseded_by', table_name='messages')
    op.drop_column('messages', 'superseded_by_id')
    op.drop_column('messages', 'superseded_at')
    # ### end Alembic commands ###
