"""add audit_query table for free SQL queries

Revision ID: 8516f1dd9d51
Revises: 7c9c487e85ba
Create Date: 2026-05-28 21:32:16.444432

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8516f1dd9d51'
down_revision: str | None = '7c9c487e85ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_query',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('user_question', sa.String(length=500), nullable=True),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('estimated_rows', sa.Integer(), nullable=True),
    sa.Column('returned_rows', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_query_conversation_created', 'audit_query', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_audit_query_result_created', 'audit_query', ['result', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_query_result_created', table_name='audit_query')
    op.drop_index('ix_audit_query_conversation_created', table_name='audit_query')
    op.drop_table('audit_query')
    # ### end Alembic commands ###
