"""add finish_reason tool_invocations usage cost_usd to messages

Revision ID: a43047be72dd
Revises: c0fb9d12fed3
Create Date: 2026-05-26 20:01:31.921236

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a43047be72dd'
down_revision: str | None = 'c0fb9d12fed3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('finish_reason', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('tool_invocations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True))
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_column('messages', 'cost_usd')
    op.drop_column('messages', 'usage')
    op.drop_column('messages', 'tool_invocations')
    op.drop_column('messages', 'finish_reason')
    # ### end Alembic commands ###
