"""add title_locked to conversations

Revision ID: ee85fab69b46
Revises: a43047be72dd
Create Date: 2026-05-26 20:25:45.504529

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee85fab69b46'
down_revision: str | None = 'a43047be72dd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title_locked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'title_locked')
    # ### end Alembic commands ###
