from app.modules.company_knowledge.domain.exceptions.exceptions import (
    AiReadingError,
    CompanyDocumentConflictError,
    CompanyDocumentFileTooLargeError,
    CompanyDocumentIndexLimitReachedError,
    CompanyDocumentInvalidError,
    CompanyDocumentNotFoundError,
    DocumentExtractionError,
    DuplicateCompanyDocumentError,
    EmbedderUnavailableError,
    UnsafeUrlError,
    UnsupportedCompanyDocumentMediaTypeError,
    WebFetchError,
    WebSourceNotFoundError,
)

__all__ = [
    "AiReadingError",
    "CompanyDocumentConflictError",
    "CompanyDocumentFileTooLargeError",
    "CompanyDocumentIndexLimitReachedError",
    "CompanyDocumentInvalidError",
    "CompanyDocumentNotFoundError",
    "DocumentExtractionError",
    "DuplicateCompanyDocumentError",
    "EmbedderUnavailableError",
    "UnsafeUrlError",
    "UnsupportedCompanyDocumentMediaTypeError",
    "WebFetchError",
    "WebSourceNotFoundError",
]
